### ISSUE TITLE
x-code9编译报文件找不到

### ISSUE THREAD

**Issue by love626947341** [QuintGao/GKAudioPlayerDemo#1]
cocoPods我都安装好了，也下载好了需要的第三方文件，AFNetWorking等PodFile里需要的，但是编译的时候在预编译文件导入的库中还是报文件找不到？但是我点击导入的头文件是可以看到需要的第三方库的。请问这是什么问题呢？

**Comment by QuintGao** [comment]
哪个文件找不到？clean一下试试呢

**Comment by love626947341** [comment]
预编译文件这些都报找不到。clean也不管用。。你的邮箱有吗？？我给你发截图

**Comment by QuintGao** [comment]
1094887059@qq.com

**Comment by 7934345** [comment]
我也是 Xcode 9.1 
捡回代码 打开workspace工程
缺少 Pods Project (直接 pod install 了)
待还原pods build 项目 提示 'GKNavigationBarConfigure.h' file not found
Pods中的GKNavigationBarViewController项目 抛错

我关注这个项目 主要是 想知道 MobileVLCKit-unstable 这个引用是怎么引入到工程的
是在pods中编译后 将产物 添加到工程中的吗?还是pods编译玩直接就能引用了 我卡到这里了 而且没找到对应的文档 只发现了 编译方式

**Comment by QuintGao** [comment]
可以先pod repo update更新下本地的资源，再pod install

**Comment by QuintGao** [comment]
关于MobileVLCKit-unstable，通过pod安装后直接就能引入了

**Comment by 7934345** [comment]
@QuintGao 谢谢啦 我这里就奇怪了 无论是OC 还是 Swift 唯独这个MobileVLCKit 无法引用
可能是我自己的原因了 我在去看看

谢谢啦

**Comment by CodeAcmen** [comment]
pods build 项目 提示 'GKNavigationBarConfigure.h' file not found

**Comment by QuintGao** [comment]
GKNavigationBarViewController的最新版本是1.3.7，你看看你那里是不是，如果不是，需要更新到最新版本

**Comment by CodeAcmen** [comment]
版本是1.3.7

**Comment by QuintGao** [comment]
@CodeAcmen 你好，请下载最新demo，GKNavigationBarViewController更新到了1.3.8。

**Comment by CodeAcmen** [comment]
@QuintGao 好的!

**Comment by CodeAcmen** [comment]
@QuintGao 更新到1.3.8之后还是那个问题. 我将podfile里的GKNavigationBarViewController注释掉 从你个人主页这下载了该库并拖进去 再编译就行了  个人建议可以将"GKNavigationBarViewController"和"GKCover"做成组件

**Comment by QuintGao** [comment]
你好，找到原因了，请先删除工程文件夹下面的pods文件夹，然后在使用pod install重新pod。原因可能是添加忽略文件时把有些不必要的文件也忽略了导致的。

**Comment by love626947341** [comment]
@7934345  我的也卡在这里了。。你的好了吗？？ MobileVLCKit-unstable

**Comment by QuintGao** [comment]
#2
