### ISSUE TITLE
大神写的太棒了，锁屏界面操作全部支持，AirPlay也有，太厉害了

### ISSUE THREAD

**Issue by ganjmeng** [QuintGao/GKAudioPlayerDemo#4]
但是发现几个小bug
1、暂停播放点击会停止播放，播放中点暂停再点播放没有效果，需要切换到下一首才恢复
2、单曲循环模式下 当前歌曲播放完成后就停住了
3、随机模式下点击上一曲下一曲会出现顺序歌曲一闪而过再显示随机歌曲的情况，上面手势操作没有效果，还是顺序播放

希望大神有空能看看，通过你这个demo学到了很多，太感谢了

**Comment by QuintGao** [comment]
问题已修复
