### ISSUE TITLE
MobileVLCKit-unstable 这个库一直安装不了呢？

### ISSUE THREAD

**Issue by Kejiasir** [QuintGao/GKAudioPlayerDemo#7]
更新过了本地 repo了，还是不行，挂了梯子也不行。。。

<img width="760" alt="qq20180830-095221 2x" src="https://user-images.githubusercontent.com/14361443/44824887-82f56100-ac3a-11e8-83cb-3ea0de7d1b96.png">

**Comment by QuintGao** [comment]
这个库有点大，网络不好就下载不了。
